# Generated by Django 5.2.5 on 2025-10-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(max_length=100)),
                ('posted_on', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='events/default.webp', null=True, upload_to='events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
