# Generated by Django 5.2.8 on 2025-11-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/default.webp', null=True, upload_to='events/'),
        ),
    ]
