# Generated by Django 5.2.8 on 2025-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default/default-event_y0hjnr.png', null=True, upload_to='events/'),
        ),
    ]
