# Generated by Django 5.2.8 on 2025-11-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='defaults/event.png', null=True, upload_to='events/'),
        ),
    ]
