# Generated by Django 5.1.2 on 2025-11-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job')], max_length=15)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('last_date', models.DateField()),
                ('posted_on', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='opportunity/default.jpg', null=True, upload_to='opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Opportunity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to="applicant's_cv")),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicants', to='opportunity.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('reported_on', models.DateField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OpportunityReport', to='opportunity.opportunity')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
