# Generated by Django 5.2.8 on 2025-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dvqujmybl/image/upload/v1764002286/default-opportunity_jzbs9w.jpg', null=True, upload_to='opportunity'),
        ),
    ]
