# Generated by Django 5.2.8 on 2025-11-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, default='default/default-opportunity_jzbs9w.jpg', null=True, upload_to='opportunity'),
        ),
    ]
