# Generated by Django 5.2.8 on 2025-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_alter_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, default='media/default/default-event_y0hjnr', null=True, upload_to='opportunity'),
        ),
    ]
