# Generated by Django 5.2.8 on 2025-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_alter_opportunity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity'),
        ),
    ]
