# Generated by Django 5.1.2 on 2025-11-07 11:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('id_type', models.CharField(max_length=30)),
                ('id_file', models.FileField(upload_to='id_proofs')),
                ('clg_id_type', models.CharField(max_length=30)),
                ('clg_id_file', models.FileField(upload_to='clg_id_proofs')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni')], max_length=15, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('enrolment_no', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('starting_year', models.IntegerField(null=True)),
                ('ending_year', models.IntegerField(null=True)),
                ('course_name', models.CharField(choices=[('BTECH', 'BTECH'), ('BA HONOURS', 'BA HONOURS')], max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pictures/default1.jpg', null=True, upload_to='profile_pictures/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlumniDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Job', 'Job'), ('Higher Studies', 'Higher Studies'), ('Startup', 'Startup'), ('Other', 'Other')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AlumniDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Self-Employed', 'Self-Employed'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Trainee', 'Trainee')], max_length=30)),
                ('organization_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30)),
                ('media', models.FileField(blank=True, null=True, upload_to='user_experience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HigherStudies', to='authentication.alumnidetails')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Others', to='authentication.alumnidetails')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(choices=[('Basic', 'Basic'), ('Inter-mediate', 'Inter-mediate'), ('Advance', 'Advance')], max_length=15)),
                ('endorsement', models.IntegerField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='user_skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Startup', to='authentication.alumnidetails')),
            ],
        ),
        migrations.CreateModel(
            name='StatusDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='status_docs')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatusDocuments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('current_year', models.IntegerField()),
                ('home_town', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StudentDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WorkingProfessional', to='authentication.alumnidetails')),
            ],
        ),
    ]
