# Generated by Django 5.2.8 on 2025-11-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='manualverification',
            name='clg_id_file',
            field=models.FileField(upload_to='clg_id_proofs/'),
        ),
        migrations.AlterField(
            model_name='manualverification',
            name='id_file',
            field=models.FileField(upload_to='id_proofs/'),
        ),
    ]
