# Generated by Django 5.1.2 on 2025-11-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/authentication/image/default1.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=30),
        ),
    ]
