# Generated by Django 5.2.5 on 2025-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_profile_pic_alter_customuser_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/default1.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
