# Generated by Django 5.2.8 on 2025-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_experience_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dvqujmybl/image/upload/v1764002286/default-avatar_tieved.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
    ]
