# Generated by Django 5.2.5 on 2025-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnidetails',
            name='current_status',
            field=models.CharField(choices=[('Job', 'Job'), ('Higher Studies', 'Higher Studies'), ('Startup', 'Startup'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course_name',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('BA HONOURS', 'BTECH')], max_length=50, null=True),
        ),
    ]
