# Generated by Django 5.1.2 on 2025-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_is_online_customuser_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30),
        ),
    ]
