# Generated by Django 5.2.5 on 2025-09-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_alumnidetails_current_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.alumnidetails')),
            ],
        ),
    ]
