# Generated by Django 5.2.5 on 2025-09-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course_name',
            field=models.CharField(choices=[('BTECH', 'BTECH'), ('BA HONOURS', 'BA HONOURS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='alumni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Startup', to='authentication.alumnidetails'),
        ),
    ]
