# Generated by Django 5.1.2 on 2025-11-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_experience_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=30),
        ),
    ]
