# Generated by Django 5.1.2 on 2025-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_experience_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=30),
        ),
    ]
