# Generated by Django 5.2.5 on 2025-09-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_course_name_alter_startup_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='alumni',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Others', to='authentication.alumnidetails'),
        ),
    ]
