# Generated by Django 5.2.5 on 2025-09-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_others_alumni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualverification',
            name='clg_id_file',
            field=models.FileField(upload_to='clg_id_proofs'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Self-Employed', 'Self-Employed'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Trainee', 'Trainee')], max_length=30)),
                ('organization_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=30)),
                ('media', models.FileField(null=True, upload_to='user_certificates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
