# Generated by Django 5.2.5 on 2025-09-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_manualverification_clg_id_file_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='user_certificates'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('proficiency', models.CharField(choices=[('Basic', 'Basic'), ('Inter-mediate', 'Inter-mediate'), ('Advance', 'Advance')], max_length=15)),
                ('endorsement', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Skill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
