# Generated by Django 5.2.5 on 2025-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_experience_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='endorsement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
