# Generated by Django 5.2.5 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_skill_media_alter_experience_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='user_experience'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='user_skills'),
        ),
    ]
