# Generated by Django 5.2.5 on 2025-09-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_experience_location_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnidetails',
            old_name='alumni',
            new_name='user',
        ),
    ]
