# Generated by Django 5.2.5 on 2025-10-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_experience_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pictures/default1.jpg', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('On-site', 'On-site')], max_length=30),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
