# Generated by Django 5.2.5 on 2025-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('On-site', 'On-site'), ('Remote', 'Remote')], max_length=30),
        ),
    ]
