# Generated by Django 5.2.5 on 2025-10-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_studentdetails_bio_alter_experience_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location_type',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], max_length=30),
        ),
    ]
